### ISSUE TITLE
关于语法高亮的一些问题

### ISSUE THREAD

**Issue by WuMrZore** [moeakwak/monaco-it#1]
你好！我想请问一下您的dark-plus和light-plus是如何弄的？我发现他们在c/c++中的语法高亮效果很明显！

**Comment by moeakwak** [comment]
我参考了这篇文章：https://segmentfault.com/a/1190000040746839
这两个主题从vscode的主题json生成得到，具体方法你可以看scripts文件夹里面有个convert_theme.js，之后的用法就和这篇文章一致了

**Comment by WuMrZore** [comment]
我刚才找到了，我使用monaco-vscode-textmate-theme-converter去转换他们，但是报错了，你是用的什么插件转化的呢？

**Comment by WuMrZore** [comment]
你代码没push，没有plus的主题(灬ꈍ ꈍ灬)，我找了半天才发现你昨天打的包，commit是前天的。。。

**Comment by moeakwak** [comment]
你再看一下呢，刚才已经push了

**Comment by WuMrZore** [comment]
我用上了，但是好像没效果。。。哭唧唧

**Comment by WuMrZore** [comment]
难道还要设置一下别的么？

**Comment by moeakwak** [comment]
光使用json是不够的。说起来很麻烦，你看一下二楼那篇文章就知道了

**Comment by WuMrZore** [comment]
我就是看的那个来的

**Comment by WuMrZore** [comment]
我再试试吧，如果有问题再麻烦你，感谢！

**Comment by WuMrZore** [comment]
已经解决，感谢咯，(*^▽^*)
